ImoveisNow/Models/Entities/Anunciante.cs
using System;
using System.Collections.Generic;

namespace ImoveisNow.Models.Entities
{
    public class Anunciante
    {
        public Anunciante(Guid id, string nome, string email, string telefone, int cidadeId, string creci, DateTime ultimoAcesso, string tipoDeAnunciante, bool ativo)
        {
            Id = id;
            Nome = nome;
            Email = email;
            Telefone = telefone;
            CidadeId = cidadeId;
            CRECI = creci;
            DataDeCadastro = DateTime.Now;
            UltimoAcesso = ultimoAcesso;
            TipoDeAnunciante = tipoDeAnunciante;
            Ativo = ativo;
        }

        protected Anunciante()
        {

        }

        public Guid Id { get; private set; }
        public string Nome { get; private set; }
        public string Email { get; private set; }
        public string Telefone { get; private set; }
        public int CidadeId { get; private set; }
        public string CRECI { get; private set; }
        public DateTime DataDeCadastro { get; private set; }
        public DateTime UltimoAcesso { get; private set; }
        public string TipoDeAnunciante { get; private set; }
        public bool Ativo { get; private set; }

        public Cidade Cidade { get; private set; }
        public ICollection<PlanoDoAnunciante> ListaDePlanoDoAnunciante { get; private set; }
        public ICollection<Anuncio> ListaDeAnuncios { get; private set; }
        public ICollection<AnunciosFavoritos> ListaDeFavoritos { get; private set; }
        public ICollection<Compra> ListaDeCompras { get; private set; }
    }
}

ImoveisNow/Models/ViewModels/Anunciante/AnuncianteFactory.cs
using ImoveisNow.Models.Entities;
using ImoveisNow.Models.Entities.Enum;
using ImoveisNow.Models.Helpers;
using System;
using System.Collections.Generic;

namespace ImoveisNow.Models.ViewModels.Anunciante
{
    public static class AnuncianteFactory
    {
        public static Entities.Anunciante CriarAnunciante(CadastroAnuncianteViewModel cadastroAnuncianteViewModel, Guid aspNetUserId)
        {
            var ativo = true;
            var tipoDeAnunciante = TipoDeAnunciante.Proprietario.GetDescription();

            return new Entities.Anunciante(
                aspNetUserId, cadastroAnuncianteViewModel.Nome, cadastroAnuncianteViewModel.Email,
                cadastroAnuncianteViewModel.Telefone, cadastroAnuncianteViewModel.CidadeId, cadastroAnuncianteViewModel.CRECI,
                DateTime.Now.Date, tipoDeAnunciante, ativo);
        }
        public static CadastroAnuncianteViewModel CriarCadastroAnuncianteViewModel(ICollection<Cidade> cidades)
        {
            var cidadeDictionary = new Dictionary<int, string>();

            foreach (var item in cidades)
                cidadeDictionary.Add(item.Id, item.Nome + " - " +item.Estado.Sigla);

            return new CadastroAnuncianteViewModel
            {
                ListaDeCidades = cidadeDictionary
            };
        }
    }
}

ImoveisNow/Models/ViewModels/Feedback/CriarFeedBackViewModel.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ImoveisNow.Models.ViewModels.Feedback
{
    public class CriarFeedBackViewModel
    {
        [Required(ErrorMessage = "Informe o Email para continuar.")]
        [DisplayName("EMAIL")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Informe o Texto para continuar.")]
        [DisplayName("TEXTO")]
        public string Texto { get; set; }
        [DisplayName("DESEJA RECEBER UM RETORNO?")]
        public bool ReceberReposta { get; set; }
    }
}

ImoveisNow/Models/ViewModels/MinhaConta/ListaDeDenunciaViewModel.cs
using System;

namespace ImoveisNow.Models.ViewModels.MinhaConta
{
    public class ListaDeDenunciaViewModel
    {
        public int Id { get; set; }
        public DateTime DataEHora { get; set; }
        public string Motivo { get; set; }
    }
}

ImoveisNow/Controllers/AnuncianteController.cs
using ImoveisNow.Models.Repository.Interface;
using ImoveisNow.Models.ViewModels.Anunciante;
using ImoveisNow.Models.ViewModels.Autenticacao;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using System;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ImoveisNow.Controllers
{
    [AllowAnonymous]
    public class AnuncianteController : Controller
    {
        private readonly IAllRepository allRepository;
        private readonly IToastNotification toastNotification;

        public AnuncianteController(IAllRepository allRepository, IToastNotification toastNotification)
        {
            this.allRepository = allRepository;
            this.toastNotification = toastNotification;
        }

        public IActionResult CadastroProprietario()
        {
            var cidades = allRepository.CidadeRepository.ObterCidades(true);
            var cadastroProprietarioViewModel = AnuncianteFactory.CriarCadastroAnuncianteViewModel(cidades);
            return View(cadastroProprietarioViewModel);
        }
        public IActionResult CadastroCorretor()
        {
            var cidades = allRepository.CidadeRepository.ObterCidades(true);
            var cadastroProprietarioViewModel = AnuncianteFactory.CriarCadastroAnuncianteViewModel(cidades);
            return View(cadastroProprietarioViewModel);
        }

        public IActionResult CadastroImobiliaria()
        {
            var cidades = allRepository.CidadeRepository.ObterCidades(true);
            var cadastroProprietarioViewModel = AnuncianteFactory.CriarCadastroAnuncianteViewModel(cidades);
            return View(cadastroProprietarioViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> CadastroProprietario(CadastroAnuncianteViewModel cadastroAnuncianteViewModel)
        {
            var checarEmail = await allRepository.UsuarioIdentityRepository.BuscarPorEmail(cadastroAnuncianteViewModel.Email);
            if (checarEmail != null)
            {
                toastNotification.AddErrorToastMessage("Falha ao realizar cadastro.");
                return View(cadastroAnuncianteViewModel);
            }

            var usuarioIdentity = UsuarioIdentityFactory.CriarUsuarioIdentityProprietario(cadastroAnuncianteViewModel);
            var resultado = await allRepository.UsuarioIdentityRepository.CriarUsuarioIdentity(usuarioIdentity, cadastroAnuncianteViewModel.Senha);
            if (resultado.Succeeded)
            {
                var usuarioId = await allRepository.UsuarioIdentityRepository.BuscarPorEmail(cadastroAnuncianteViewModel.Email);
                var anunciante = AnuncianteFactory.CriarAnunciante(cadastroAnuncianteViewModel, new Guid(usuarioId.Id));
                await allRepository.AnuncianteRepository.CriarAnunciante(anunciante);
                await allRepository.UsuarioIdentityRepository.CriarClaimsDoUsuario(usuarioIdentity, new Claim("Anunciante", "True"));
                await allRepository.UsuarioIdentityRepository.CriarClaimsDoUsuario(usuarioIdentity, new Claim("Proprietario", "True"));
                toastNotification.AddInfoToastMessage("Cadastro realizado com sucesso!");

                return RedirectToAction("Entrar", "Autenticacao");
            }
            toastNotification.AddErrorToastMessage("Falha ao realizar cadastro.");
            return View(cadastroAnuncianteViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> CadastroCorretor(CadastroAnuncianteViewModel cadastroAnuncianteViewModel)
        {
            var checarEmail = await allRepository.UsuarioIdentityRepository.BuscarPorEmail(cadastroAnuncianteViewModel.Email);
            if (checarEmail != null)
            {
                toastNotification.AddErrorToastMessage("Falha ao realizar cadastro.");
                return View(cadastroAnuncianteViewModel);
            }

            var usuarioIdentity = UsuarioIdentityFactory.CriarUsuarioIdentityProprietario(cadastroAnuncianteViewModel);
            var resultado = await allRepository.UsuarioIdentityRepository.CriarUsuarioIdentity(usuarioIdentity, cadastroAnuncianteViewModel.Senha);
            if (resultado.Succeeded)
            {
                var usuarioId = await allRepository.UsuarioIdentityRepository.BuscarPorEmail(cadastroAnuncianteViewModel.Email);
                var anunciante = AnuncianteFactory.CriarAnunciante(cadastroAnuncianteViewModel, new Guid(usuarioId.Id));
                await allRepository.AnuncianteRepository.CriarAnunciante(anunciante);
                await allRepository.UsuarioIdentityRepository.CriarClaimsDoUsuario(usuarioIdentity, new Claim("Anunciante", "True"));
                await allRepository.UsuarioIdentityRepository.CriarClaimsDoUsuario(usuarioIdentity, new Claim("Corretor", "True"));
                toastNotification.AddInfoToastMessage("Cadastro realizado com sucesso!");

                return RedirectToAction("Entrar", "Autenticacao");
            }
            toastNotification.AddErrorToastMessage("Falha ao realizar cadastro.");
            return View(cadastroAnuncianteViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> CadastroImobiliaria(CadastroAnuncianteViewModel cadastroAnuncianteViewModel)
        {
            var checarEmail = await allRepository.UsuarioIdentityRepository.BuscarPorEmail(cadastroAnuncianteViewModel.Email);
            if (checarEmail != null)
            {
                toastNotification.AddErrorToastMessage("Falha ao realizar cadastro.");
                return View(cadastroAnuncianteViewModel);
            }

            var usuarioIdentity = UsuarioIdentityFactory.CriarUsuarioIdentityProprietario(cadastroAnuncianteViewModel);
            var resultado = await allRepository.UsuarioIdentityRepository.CriarUsuarioIdentity(usuarioIdentity, cadastroAnuncianteViewModel.Senha);
            if (resultado.Succeeded)
            {
                var usuarioId = await allRepository.UsuarioIdentityRepository.BuscarPorEmail(cadastroAnuncianteViewModel.Email);
                var anunciante = AnuncianteFactory.CriarAnunciante(cadastroAnuncianteViewModel, new Guid(usuarioId.Id));
                await allRepository.AnuncianteRepository.CriarAnunciante(anunciante);
                await allRepository.UsuarioIdentityRepository.CriarClaimsDoUsuario(usuarioIdentity, new Claim("Anunciante", "True"));
                await allRepository.UsuarioIdentityRepository.CriarClaimsDoUsuario(usuarioIdentity, new Claim("Imobiliaria", "True"));
                toastNotification.AddInfoToastMessage("Cadastro realizado com sucesso!");

                return RedirectToAction("Entrar", "Autenticacao");
            }
            toastNotification.AddErrorToastMessage("Falha ao realizar cadastro.");
            return View(cadastroAnuncianteViewModel);
        }
    }
}

ImoveisNow/Controllers/DenunciaController.cs
using ImoveisNow.Models.Repository.Interface;
using ImoveisNow.Models.ViewModels.Denuncia;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;

namespace ImoveisNow.Controllers
{
    [Authorize(Policy = "Administrador")]
    public class DenunciaController : Controller
    {
        private readonly IAllRepository allRepository;
        private readonly IToastNotification toastNotification;

        public DenunciaController(IAllRepository allRepository, IToastNotification toastNotification)
        {
            this.allRepository = allRepository;
            this.toastNotification = toastNotification;
        }

        public IActionResult AvaliarDenuncia(int id)
        {
            var denuncia = allRepository.DenunciaRepository.BuscarPorId(id, true);
            var avaliarDenunciaViewModel = DenunciaFactory.CriarAvaliarDenunciaViewModel(denuncia);
            return View(avaliarDenunciaViewModel);
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult NovaDenuncia(DenunciarAnuncioViewModel denunciarAnuncioViewModel)
        {
            var denuncia = DenunciaFactory.CriarDenuncia(denunciarAnuncioViewModel);
            allRepository.DenunciaRepository.CriarDenuncia(denuncia);
            toastNotification.AddInfoToastMessage("Reporte de problemas enviado!");
            return RedirectToAction("Detalhes", "Anuncio", new { Id = denunciarAnuncioViewModel.AnuncioId });
        }

        public IActionResult VereditoAcatar(int id)
        {
            var denuncia = allRepository.DenunciaRepository.BuscarPorId(id, true);
            denuncia.DenunciaAprovada();
            allRepository.DenunciaRepository.Atualizar(denuncia);
            toastNotification.AddInfoToastMessage("Veredito gravado!");
            return RedirectToAction("Admin", "MinhaConta");
        }

        public IActionResult VereditoIgnorar(int id)
        {
            var denuncia = allRepository.DenunciaRepository.BuscarPorId(id, true);
            denuncia.DenunciaNegada();
            allRepository.DenunciaRepository.Atualizar(denuncia);
            toastNotification.AddInfoToastMessage("Veredito gravado!");
            return RedirectToAction("Admin", "MinhaConta");
        }
    }
}

ImoveisNow/Controllers/MinhaContaController.cs
using ImoveisNow.Models.Repository.Interface;
using ImoveisNow.Models.ViewModels.MinhaConta;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace ImoveisNow.Controllers
{
    [Authorize]
    public class MinhaContaController : Controller
    {
        private readonly IAllRepository allRepository;

        public MinhaContaController(IAllRepository allRepository)
        {
            this.allRepository = allRepository;
        }

        public async Task<IActionResult> Index()
        {
            var usuarioLogadoId = allRepository.UsuarioIdentityRepository.UsuarioLogadoId();
            var claims = await allRepository.UsuarioIdentityRepository.BuscarClaims(usuarioLogadoId);
            //ToDo: Melhorar o Redirecionamento
            if (claims != null)
            {
                foreach (var claim in claims)
                {
                    if (claim.Type == "Administrador")
                    {
                        return RedirectToAction("Admin");
                    }
                    if (claim.Type == "Anunciante")
                    {
                        return RedirectToAction("Anunciante");
                    }
                }
            }
            return NotFound();
        }

        [Authorize(Policy = "Anunciante")]
        public IActionResult Anunciante()
        {
            var usuarioId = allRepository.UsuarioIdentityRepository.UsuarioLogadoId();
            //var anunciante = allRepository.AnuncianteRepository.BuscarAnunciantePorId(new Guid(usuarioId), true);
            var favoritos = allRepository.AnunciosFavoritosRepository.BuscarTodosDoUsuario(new Guid(usuarioId), true);
            var contato = allRepository.ContatosRecebidosRepository.BuscarTodosDoUsuario(new Guid(usuarioId), true);
            //var planoAtivo = allRepository.AnuncianteRepository.BuscarPlanoAtivoPorAnuncianteId(new Guid(usuarioId, true);
            var minhaContaAnuncianteViewModel = MinhaContaFactory.CriarMinhaContaAnuncianteViewModel(favoritos, contato);
            return View(minhaContaAnuncianteViewModel);
        }

        [Authorize(Policy = "Administrador")]
        public IActionResult Admin()
        {
            var numeroDeVisualizacoes = allRepository.VisualizacoesRepository.ObterNumeroDeVisualizacoes(true);
            var numeroDeAnuncios = allRepository.AnuncioRepository.ObterNumeroDeAnunciosAtivo(true);
            var numeroDeAnunciantes = allRepository.AnuncianteRepository.ObterNumeroDeAnunciantesAtivo(true);
            var numeroDePlanosPremiums = allRepository.PlanoPremiumRepository.ObterNumeroDePlanosPremiumsAtivo(true);
            var denuncias = allRepository.DenunciaRepository.ObterCincoDenunciasNaoAvaliadas(true);
            var feedback = allRepository.FeedbackRepository.ObterCincoFeedBacksNaoArquivados(true);
            var minhaContaAdminViewModel = MinhaContaFactory.CriarMinhaContaAdminViewModel(numeroDeVisualizacoes, numeroDeAnuncios, numeroDeAnunciantes, numeroDePlanosPremiums, denuncias, feedback);
            return View(minhaContaAdminViewModel);
        }

        public IActionResult VisualizarContato(int id)
        {
            var contato = allRepository.ContatosRecebidosRepository.BuscasPorId(id, true);

            var xpto = MinhaContaFactory.CriarContato(contato);

            return View(xpto);
        }

        public IActionResult Arquivar(int id)
        {
            var contato = allRepository.ContatosRecebidosRepository.BuscasPorId(id, true);
            contato.Arquivar();
            allRepository.ContatosRecebidosRepository.Arquivar(contato);

            return RedirectToAction("Anunciante");
        }
    }
}

ImoveisNow/Controllers/PlanoPremiumController.cs
using ImoveisNow.Models.Repository.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ImoveisNow.Controllers
{
    [Authorize(Policy = "Anunciante")]
    public class PlanoPremiumController : Controller
    {
        private readonly IAllRepository allRepository;

        public PlanoPremiumController(IAllRepository allRepository)
        {
            this.allRepository = allRepository;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult FormaDePagamento(int id)
        {
            var usuario = allRepository.UsuarioIdentityRepository.UsuarioLogadoId();
            return View();
        }
    }
}

ImoveisNow/Views/MinhaConta/Admin.cshtml
@model ImoveisNow.Models.ViewModels.MinhaConta.MinhaContaAdminViewModel

@{
    ViewData["Title"] = "Admin";
    Layout = "~/Views/Shared/_LayoutContainerFluid.cshtml";
}

<div class="container mt-4">
    <div class="row">
        <div class="col-md-3 col-sm-6">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex no-block">
                        <div class="mr-4 align-self-center"><i class="far fa-eye color-theme fa-3x"></i></div>
                        <div class="align-self-center">
                            <h6 class="text-muted m-t-10 m-b-0">Visualizações</h6>
                            <h2 class="m-t-0">@Model.NumeroDeVisualizacoes</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex no-block">
                        <div class="mr-4 align-self-center"><i class="fas fa-home color-theme fa-3x"></i></div>
                        <div class="align-self-center">
                            <h6 class="text-muted m-t-10 m-b-0">Anúncios</h6>
                            <h2 class="m-t-0">@Model.NumeroDeAnunciosAtivos</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex no-block">
                        <div class="mr-4 align-self-center"><i class="fas fa-users color-theme fa-3x"></i></div>
                        <div class="align-self-center">
                            <h6 class="text-muted m-t-10 m-b-0">Anunciantes</h6>
                            <h2 class="m-t-0">@Model.NumeroDeAnunciantesAtivos</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex no-block">
                        <div class="mr-4 align-self-center"><i class="fas fa-user-plus color-theme fa-3x"></i></div>
                        <div class="align-self-center">
                            <h6 class="text-muted m-t-10 m-b-0">Contas Premium</h6>
                            <h2 class="m-t-0">@Model.NumeroDePlanosPremiumAtivos</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h4 class="text-muted compartilhar">Visualizações por mês</h4>
                    @* TODO: Obter os dados quantitativos de Visualizações e passar como parâmetro via data-attribute *@
                    <canvas id="chart"></canvas>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h4 class="text-muted">Feedbacks</h4>
                    <div class="table-responsive">
                        @if (Model.Feedbacks.Any())
                        {
                            <table class="table table-hover table-click">
                                <thead>
                                    <tr>
                                        <th>
                                            #
                                        </th>
                                        <th>
                                            Data de Criação
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var feedback in Model.Feedbacks)
                                    {
                                        <tr>
                                            <td>
                                                <a href="@Url.Action("LerFeedBack", "Feedback", new { id = feedback.Id })">@Html.DisplayFor(modelItem => feedback.Id)</a>
                                            <td>
                                                @feedback.DataEHora.ToShortDateString()
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        }
                        else
                        {
                            <p>Não foi encontrando nenhuma denúncia.</p>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="text-muted">Denúncias</h4>
                    <div class="table-responsive">
                        @if (Model.Denuncias.Any())
                        {
                            <table class="table table-hover table-click">
                                <thead>
                                    <tr>
                                        <th>
                                            #
                                        </th>
                                        <th>
                                            Data de Criação
                                        </th>
                                        <th>
                                            Motivo
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var denuncia in Model.Denuncias)
                                    {
                                        <tr>
                                            <td>
                                                <a href="@Url.Action("AvaliarDenuncia", "Denuncia", new { id = denuncia.Id })">@Html.DisplayFor(modelItem => denuncia.Id)</a>
                                            </td>
                                            <td>
                                                @denuncia.DataEHora.ToShortDateString()
                                            </td>
                                            <td>
                                                @denuncia.Motivo
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        }
                        else
                        {
                            <p>Não foi encontrando nenhuma denúncia.</p>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
    <script>
        $Visualizacao = '@Model.NumeroDeVisualizacoes'
    </script>
    <script src="~/js/app/admin.js"></script>
}

ImoveisNow/Views/MinhaConta/Anunciante.cshtml
@model ImoveisNow.Models.ViewModels.MinhaConta.MinhaContaAnuncianteViewModel

@{
    ViewData["Title"] = "Anunciante";
    Layout = "~/Views/Shared/_LayoutContainerFluid.cshtml";
}

<div class="container">
    <div class="card mt-4">
        <div class="card-body">
            <label class="text-muted">ANÚNCIOS</label><label class="float-right">Plano Premium</label><br />
            <label class="fs-18"><b>0</b></label> <label class="text-muted">anúncios ativos</label>
            <div class="progress">
                <div class="progress-bar w-0" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <label class="text-muted">0</label><label class="text-muted float-right">8</label>
            <br />
            <label class="fs-18"><b>0</b></label> <label class="text-muted">anúncios em destaque</label>
            <div class="progress">
                <div class="progress-bar w-0" role="progressbar" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <label class="text-muted">1</label><label class="text-muted float-right">3</label>
            <br />
            <br />
            <a asp-area="" asp-action="Index" asp-controller="PlanoPremium" class="btn-link-theme">ADQUIRIR PLANO</a>
            <a asp-area="" asp-action="MeusAnuncios" asp-controller="Anuncio" class="btn-link-theme float-right">GERENCIAR MEUS ANÚNCIOS</a>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="text-muted">Contatos Recebidos</h4>
                    <div class="table-responsive">
                        @if (Model.ContatosRecebidos.Any())
                        {
                            <table class="table table-hover table-click">
                                <thead>
                                    <tr>
                                        <th>
                                            #
                                        </th>
                                        <th>
                                            Titulo
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var contato in Model.ContatosRecebidos)
                                    {
                                        <tr>
                                            <td>
                                                <a href="@Url.Action(" VisualizarContato", "MinhaConta" , new { id=contato.Id })">@Html.DisplayFor(modelItem => @contato.Id)</a>
                                            </td>
                                            <td>
                                                @contato.Titulo
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        }
                        else
                        {
                            <p>Não foi encontrando nenhuma denúncia.</p>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="text-muted">Favoritos</h4>
                    <div class="table-responsive">
                        @if (Model.AnunciosFavoritos.Any())
                        {
                            <table class="table table-hover table-click">
                                <thead>
                                    <tr>
                                        <th>
                                            Título
                                        </th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var favorito in Model.AnunciosFavoritos)
                                    {
                                        <tr>
                                            <td>
                                                <a href="@Url.Action(" Detalhes", "Anuncio" , new { id=favorito.Id })">@Html.DisplayFor(modelItem => @favorito.Titulo)</a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        }
                        else
                        {
                            <p>Não foi encontrando nenhuma denúncia.</p>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <h6 class="text-muted ml-2 mb-3">Envie o Feedback de como estar sendo a sua experiência no Imóveis Now</h6>
                    <button class="btn btn-theme feedback mx-1"><i class="fas fa-thumbs-up fs-14"></i> Enviar FeedBack</button>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <h6 class="text-muted ml-2 mb-3">Adicione o Imóveis Now na sua Tela Inicial !</h6>
                    <button onclick="install()" class="btn btn-theme">
                        Adicionar agora !
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalFeedback">
    <partial name="_CriarFeedBack" model="Model.CriarFeedBack" />
</div>
<!--Teste PWA-->




@section scripts{
    <script src="~/js/app/anunciante.js"></script>
    <script src="~/js/helpers/requiredHelper.js"></script>
}

ImoveisNow/Views/MinhaConta/Favoritos.cshtml
@*@model ImoveisNow.Models.ViewModels.MinhaConta.MinhaContaAnuncianteViewModel*@

@{
    ViewData["Title"] = "Anunciante";
    Layout = "~/Views/Shared/_LayoutContainerFluid.cshtml";
}

<div class="container">
    <p>Favoritos</p>
</div>