ImoveisNow/Controllers/AutenticacaoController.cs
using ImoveisNow.Models.Helpers;
using ImoveisNow.Models.Repository.Interface;
using ImoveisNow.Models.ViewModels.Autenticacao;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using System;
using System.Threading.Tasks;

namespace ImoveisNow.Controllers
{
    [AllowAnonymous]
    public class AutenticacaoController : Controller
    {
        private readonly IAllRepository allRepository;
        private readonly IToastNotification toastNotification;

        public AutenticacaoController(IAllRepository allRepository, IToastNotification toastNotification)
        {
            this.allRepository = allRepository;
            this.toastNotification = toastNotification;
        }

        public IActionResult Entrar()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Entrar(LoginViewModel loginViewModel)
        {
            var usuarioIdentity = await allRepository.UsuarioIdentityRepository.BuscarPorEmail(loginViewModel.Email);
            var usuarioIdentityResult = await allRepository.UsuarioIdentityRepository.RealizarLogin(usuarioIdentity, loginViewModel.Senha);
            var anunciante = allRepository.AnuncianteRepository.BuscarAnunciantePorId(new Guid(usuarioIdentity.Id), true);
            if (usuarioIdentityResult.Succeeded)
            {
                Response.Cookies.Append("EmailUsuarioIdentity", usuarioIdentity.Email, new CookieOptions() { IsEssential = true });
                Response.Cookies.Append("NomeUsuarioIdentity", StringHelper.GetFirstName(anunciante.Nome), new CookieOptions() { IsEssential = true });
                Response.Cookies.Append("IdUsuarioIdentity", usuarioIdentity.Id, new CookieOptions() { IsEssential = true });
                toastNotification.AddInfoToastMessage("Login Realizado com Sucesso!");
                return RedirectToAction("Index", "Home");
            }
            else
            {
                toastNotification.AddErrorToastMessage("Login ou Senha Incorreto!");
                return View(loginViewModel);
            }
        }

        public IActionResult Cadastro()
        {
            var usuario = allRepository.UsuarioIdentityRepository.UsuarioLogadoId();

            if (usuario != null)
            {
                toastNotification.AddInfoToastMessage("Ops!");
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View();
            }
        }

        public async Task<IActionResult> Sair()
        {
            await allRepository.UsuarioIdentityRepository.Sair();
            toastNotification.AddSuccessToastMessage("LogOff Realizado!");
            return RedirectToAction("Entrar");
        }

        public IActionResult AcessoNegado()
        {
            return View();
        }
    }
}

ImoveisNow/Controllers/MinhaContaController.cs
using ImoveisNow.Models.Repository.Interface;
using ImoveisNow.Models.ViewModels.MinhaConta;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace ImoveisNow.Controllers
{
    [Authorize]
    public class MinhaContaController : Controller
    {
        private readonly IAllRepository allRepository;

        public MinhaContaController(IAllRepository allRepository)
        {
            this.allRepository = allRepository;
        }

        public async Task<IActionResult> Index()
        {
            var usuarioLogadoId = allRepository.UsuarioIdentityRepository.UsuarioLogadoId();
            var claims = await allRepository.UsuarioIdentityRepository.BuscarClaims(usuarioLogadoId);
            //ToDo: Melhorar o Redirecionamento
            if (claims != null)
            {
                foreach (var claim in claims)
                {
                    if (claim.Type == "Administrador")
                    {
                        return RedirectToAction("Admin");
                    }
                    if (claim.Type == "Anunciante")
                    {
                        return RedirectToAction("Anunciante");
                    }
                }
            }
            return NotFound();
        }

        [Authorize(Policy = "Anunciante")]
        public IActionResult Anunciante()
        {
            var usuarioId = allRepository.UsuarioIdentityRepository.UsuarioLogadoId();
            //var anunciante = allRepository.AnuncianteRepository.BuscarAnunciantePorId(new Guid(usuarioId), true);
            var favoritos = allRepository.AnunciosFavoritosRepository.BuscarTodosDoUsuario(new Guid(usuarioId), true);
            var contato = allRepository.ContatosRecebidosRepository.BuscarTodosDoUsuario(new Guid(usuarioId), true);
            //var planoAtivo = allRepository.AnuncianteRepository.BuscarPlanoAtivoPorAnuncianteId(new Guid(usuarioId, true);
            var minhaContaAnuncianteViewModel = MinhaContaFactory.CriarMinhaContaAnuncianteViewModel(favoritos, contato);
            return View(minhaContaAnuncianteViewModel);
        }

        [Authorize(Policy = "Administrador")]
        public IActionResult Admin()
        {
            var numeroDeVisualizacoes = allRepository.VisualizacoesRepository.ObterNumeroDeVisualizacoes(true);
            var numeroDeAnuncios = allRepository.AnuncioRepository.ObterNumeroDeAnunciosAtivo(true);
            var numeroDeAnunciantes = allRepository.AnuncianteRepository.ObterNumeroDeAnunciantesAtivo(true);
            var numeroDePlanosPremiums = allRepository.PlanoPremiumRepository.ObterNumeroDePlanosPremiumsAtivo(true);
            var denuncias = allRepository.DenunciaRepository.ObterCincoDenunciasNaoAvaliadas(true);
            var feedback = allRepository.FeedbackRepository.ObterCincoFeedBacksNaoArquivados(true);
            var minhaContaAdminViewModel = MinhaContaFactory.CriarMinhaContaAdminViewModel(numeroDeVisualizacoes, numeroDeAnuncios, numeroDeAnunciantes, numeroDePlanosPremiums, denuncias, feedback);
            return View(minhaContaAdminViewModel);
        }

        public IActionResult VisualizarContato(int id)
        {
            var contato = allRepository.ContatosRecebidosRepository.BuscasPorId(id, true);

            var xpto = MinhaContaFactory.CriarContato(contato);

            return View(xpto);
        }

        public IActionResult Arquivar(int id)
        {
            var contato = allRepository.ContatosRecebidosRepository.BuscasPorId(id, true);
            contato.Arquivar();
            allRepository.ContatosRecebidosRepository.Arquivar(contato);

            return RedirectToAction("Anunciante");
        }
    }
}

ImoveisNow/Controllers/PlanoPremiumController.cs
using ImoveisNow.Models.Repository.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ImoveisNow.Controllers
{
    [Authorize(Policy = "Anunciante")]
    public class PlanoPremiumController : Controller
    {
        private readonly IAllRepository allRepository;

        public PlanoPremiumController(IAllRepository allRepository)
        {
            this.allRepository = allRepository;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult FormaDePagamento(int id)
        {
            var usuario = allRepository.UsuarioIdentityRepository.UsuarioLogadoId();
            return View();
        }
    }
}

ImoveisNow/Views/Shared/_Footer.cshtml
<!--XL, LG, MD-->
<div class="col-12 d-none d-sm-block">
    <div class="row justify-content-center">
        <div class="col-md-9 col-sm-12 py-3">
            <div class="row justify-content-center">
                <div class="col-3 border-right-1">
                    <div class="row px-4 mb-2"><a><h5 class="text-white">Anúncios</h5></a></div>
                    <div class="row px-4 mb-1"><a asp-area="" asp-controller="Anuncio" asp-action="Index" class="text-white">Comprar</a></div>
                    <div class="row px-4 mb-1"><a asp-area="" asp-controller="Anuncio" asp-action="Index" class="text-white">Alugar</a></div>
                    @*<div class="row px-4 mb-1"><a asp-area="" asp-controller="Anuncio" asp-action="Index" class="text-white">Financiável</a></div>*@
                </div>
                <div class="col-3 border-right-1">
                    <div class="row px-4 mb-2"><a><h5 class="text-white">Institucional</h5></a></div>
                    <div class="row px-4 mb-1"><a asp-area="" asp-controller="Home" asp-action="Sobre" class="text-white">Sobre</a></div>
                    <div class="row px-4 mb-1"><a asp-area="" asp-controller="Home" asp-action="Contato" class="text-white">Contato</a></div>
                </div>
                <div class="col-3">
                    <div class="row px-4 mb-2"><h5 class="text-white">Anunciante</h5></div>
                    <div class="row px-4 mb-1"><a asp-area="" asp-controller="Anuncio" asp-action="CategoriaDoNovoAnuncio" class="text-white">Anunciar</a></div>
                    <div class="row px-4 mb-1"><a asp-area="" asp-controller="Autenticacao" asp-action="Cadastro" class="text-white">Cadastra-se</a></div>
                    <div class="row px-4 mb-1"><a asp-area="" asp-controller="Home" asp-action="DuvidasFrequentes" class="text-white">Dúvidas</a></div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row bg-theme-dark py-2 pl-1">
    <div class="col-md-12 d-none d-sm-block">
        <!--XL, LG, MD, SM-->
        <label class="text-white m-0">
            Copyright © @DateTime.Now.Year - Gustavo Felix.
            <br />Todos os direitos reservados.
        </label>
        <div class="float-right pt-3"><a asp-area="" asp-controller="Home" asp-action="Legal" class="text-white">Termos de Uso e Póliticas de Privacidade</a></div>
    </div>
    <!--XS-->
    <div class="col-md-12">
        <div class="row justify-content-center d-lg-none d-md-none d-sm-none">
            <div class="col-md-12">
                <div class="row justify-content-center">
                    <label class="text-white m-0">
                        Copyright © @DateTime.Now.Year - Gustavo Felix.
                        <br />Todos os direitos reservados.
                    </label>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="float-right pt-3"><a asp-area="" asp-controller="Home" asp-action="Legal" class="text-white">Termos de Uso e Políticas de Privacidade</a></div>
            </div>
        </div>
    </div>
</div>

ImoveisNow/Views/Shared/_LayoutContainerFluid.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="author" content="Gustavo Felix Gomes">

    <!--Responsive-->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!--Title-->
    <title>@ViewData["Title"] - Imóveis Now</title>

    <!--Manifest-->
    <link rel="manifest" href="/manifest.json" />

    <!--Bootstrap Core CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!--Font-Awesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <!--Custom CSS-->
    <link rel="stylesheet" href="~/css/app.css" />

    <!--Sidebar-->
    <link href="~/css/sidebar.css" rel="stylesheet" />

    <!-- Another CSS -->
    @RenderSection("Pagestyles", required: false)

</head>
<body>
    <!--Media Query-->
    @*<div class="media-query">
        <button class="btn btn-danger d-sm-none">XS</button>
        <button class="btn btn-warning d-none d-sm-block d-md-none">SM</button>
        <button class="btn btn-success d-none d-md-block d-lg-none">MD</button>
        <button class="btn btn-info d-none d-lg-block d-xl-none">LG</button>
        <button class="btn btn-primary d-none d-xl-block">XL</button>
    </div>*@
    <nav class="navbar navbar-expand-md p-0 bg-theme">
        <!--NavBar-->
        <div class="collapse navbar-collapse">
            <div class="nav-item pl-3">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand text-white logo">Imóveis Now</a>
            </div>
            <div class="nav-item">
                <a asp-area="" asp-controller="Anuncio" asp-action="Index" class="nav-link text-white">COMPRAR</a>
            </div>
            <div class="nav-item mr-auto">
                <a asp-area="" asp-controller="Anuncio" asp-action="Alugar" class="nav-link text-white">ALUGAR</a>
            </div>
            @await Component.InvokeAsync("NavbarComponent")
        </div>

        <!--NavBar Collapse-->
        <!--ToDo:Remover esse Style-->
        <div class="container-fluid navbar-toggler p-0" data-toggle="collapse" style="height:68px; margin-top:-8px;">
            <div class="nav-item">
                <a href="#" class="nav-link text-white menu"><i class="fas fa-bars"></i></a>
            </div>
            <div class="nav-item">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link text-white logo px-0">Imóveis Now</a>
            </div>
            <div class="nav-item">
                @await Component.InvokeAsync("NavbarComponent")
            </div>
        </div>
    </nav>

    <!--Sidebar-->
    <div id="wrapper">
        <partial name="_MenuLateral" />

        <!--Page Content-->
        <div class="container-fluid p-0">
            @RenderBody()
        </div>
    </div>

    <footer class="container-fluid footer">
        <partial name="_Footer" />
    </footer>

    <!--Jquery-->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.js"></script>

    <!--Bootstrap Core JavaScript-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!--SweetAlert2-->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>

    <!--Noty JS-->
    @await Component.InvokeAsync("NToastNotify")

    <!--Custom JS-->
    <script src="~/js/app/app.js"></script>

    <!--Another JS-->
    @RenderSection("Scripts", required: false)

</body>
</html>

ImoveisNow/Views/Shared/_LayoutSemNavbar.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="author" content="Gustavo Felix Gomes">

    <!--Responsive-->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!--Title-->
    <title>@ViewData["Title"] - Imóveis Now</title>

    <!--Manifest-->
    <link rel="manifest" href="/manifest.json" />

    <!--Bootstrap Core CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!--Font-Awesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <!--Custom CSS-->
    <link rel="stylesheet" href="~/css/app.css" />

    <!--Another CSS-->
    @RenderSection("Pagestyles", required: false)

</head>
<body class="bg-theme">
    @*<div class="media-query">
        <button class="btn btn-danger d-sm-none">XS</button>
        <button class="btn btn-warning d-none d-sm-block d-md-none">SM</button>
        <button class="btn btn-success d-none d-md-block d-lg-none">MD</button>
        <button class="btn btn-info d-none d-lg-block d-xl-none">LG</button>
        <button class="btn btn-primary d-none d-xl-block">XL</button>
    </div>*@
    <!--Page Content-->
    <div class="container-fluid p-2">
        @RenderBody()
    </div>

    <footer class="container-fluid footer">
        <partial name="_Footer" />
    </footer>

    <!--Jquery-->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.js"></script>

    <!--Bootstrap Core JavaScript-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!--SweetAlert2-->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>

    <!--Noty JS-->
    @await Component.InvokeAsync("NToastNotify")

    <!--Custom JS-->
    <script src="~/js/app/app.js"></script>

    <!-- Another JS -->
    @RenderSection("Scripts", required: false)

</body>
</html>

ImoveisNow/Views/Shared/_MenuLateral.cshtml
<!--ToDo: Ajustar Menu Lateral-->

<div class="sidebar">
    <div class="bg-theme navbar-collapse">
        <button class="ml-3 m-2 btn btn-outline-white menu">FECHAR</button>
    </div>
    <a asp-area="" asp-controller="Anuncio" asp-action="Index" class="nav-link color-theme mt-3"><h6>COMPRAR</h6></a>
    <a asp-area="" asp-controller="Anuncio" asp-action="Index" class="nav-link color-theme"><h6>ALUGAR</h6></a>
    <a asp-area="" asp-controller="Anuncio" asp-action="CategoriaDoNovoAnuncio" class="nav-link color-theme"><h6>ANUNCIAR</h6></a>
</div>

ImoveisNow/Views/Shared/_NavbarEntrar.cshtml
 <!--XL, LG, MD-->
<div class="nav-item d-none d-md-block">
    <a asp-area="" asp-controller="Anuncio" asp-action="CategoriaDoNovoAnuncio" class="nav-link text-white">ANUNCIAR</a>
</div>
<div class="nav-item d-none d-md-block mr-1">
    <a asp-area="" asp-controller="Autenticacao" asp-action="Entrar" class="nav-link text-white">ENTRAR</a>
</div>

<!--SM, XS-->
<div class="d-md-none d-sm-block d-sm-none">
    <div class="nav-item">
        <a asp-area="" asp-controller="Autenticacao" asp-action="Entrar" class="nav-link text-white">ENTRAR</a>
    </div>
</div>

ImoveisNow/Views/Shared/_NavbarSair.cshtml
@{
    var nomeUsuario = this.Context.Request.Cookies["NomeUsuarioIdentity"];
}

<!--XL, LG, MD-->
<div class="nav-item d-none d-md-block">
    <a asp-area="" asp-controller="Anuncio" asp-action="CategoriaDoNovoAnuncio" class="nav-link text-white">ANUNCIAR</a>
</div>

<!--XL, LG, MD, SM-->
<div class="nav-item dropdown d-none d-sm-block mr-2">
    <a class="nav-link dropdown-toggle text-white" href="" data-toggle="dropdown"><i class="fs-18 fas fa-user-circle"></i> @nomeUsuario</a>
    <div class="dropdown-menu dropdown-menu-right">
        <a class="dropdown-item text-muted" asp-area="" asp-controller="MinhaConta" asp-action="Index">MINHA CONTA</a>
        <a class="dropdown-item text-muted" asp-area="" asp-controller="Anuncio" asp-action="MeusAnuncios">MEUS ANÚNCIO</a>
        <a class="dropdown-item text-muted" asp-area="" asp-controller="PlanoPremium" asp-action="Index">PLANO PREMIUM</a>
        <a class="dropdown-item text-muted" asp-area="" asp-controller="Autenticacao" asp-action="Sair">SAIR</a>
    </div>
</div>

<!--XS-->
<div class="nav-item dropdown d-lg-none d-md-none d-sm-none mr-1">
    <a class="nav-link dropdown-toggle text-white" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><b data-toggle="tooltip" data-placement="top" title=""></b><i class="fs-18 fas fa-user-circle"></i></a>
    <div class="dropdown-menu dropdown-menu-right">
        <a class="dropdown-item text-muted" asp-area="" asp-controller="MinhaConta" asp-action="Index">MINHA CONTA</a>
        <a class="dropdown-item text-muted" asp-area="" asp-controller="Anuncio" asp-action="MeusAnuncios">MEUS ANÚNCIO</a>
        <a class="dropdown-item text-muted" asp-area="" asp-controller="PlanoPremium" asp-action="Index">PLANO PREMIUM</a>
        <a class="dropdown-item text-muted" asp-area="" asp-controller="Autenticacao" asp-action="Sair">SAIR</a>
    </div>
</div>

ImoveisNow/Views/Shared/_SemConexao.cshtml
<div align="center">
    <h3>Sem Conexão a internet</h3>
</div>